/* h2_get.c - HTTP/2 requests over one TLS connection with brisk_h2_*. The interop run drives it.
 *
 *   h2_get [options] host [port] path        port defaults to 443
 *     -c FILE     trust only this PEM bundle (default: the system bundle)
 *     -m METHOD   request method (default GET, or POST when a body is given)
 *     -d FILE     request body from FILE
 *     -D N        request body of N generated bytes: byte i = i % 251
 *     -n N        N requests of path in parallel on one connection (1..4, default 1)
 *     -r R        R rounds of those N requests, one after the other (default 1)
 *     -q          print "status S bytes B fnv H" per response instead of the body
 *
 * Response headers go to stderr as "< name: value". Exit status 0 when every response arrived
 * complete (any HTTP status), 1 on usage errors, 2 on a failure ("brisk: ..." on stderr).
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "brisk.h"
#include "example_util.h"

static void on_header(void *ctx, const char *name, size_t name_len, const char *value,
                      size_t value_len)
{
    (void)ctx;
    fprintf(stderr, "< %.*s: %.*s\n", (int)name_len, name, (int)value_len, value);
}

/* Read the response of s; print it (or its size and FNV-1a 32 with quiet). */
static int fetch(brisk_h2_stream *s, int quiet)
{
    unsigned char buf[4096];
    unsigned long fnv = 2166136261UL, total = 0;
    int status, n, i;
    int rc = brisk_h2_response(s, &status, on_header, NULL);
    if (rc != BRISK_OK) {
        return rc;
    }
    while ((n = brisk_h2_read(s, buf, sizeof buf)) > 0) {
        for (i = 0; i < n; i++) {
            fnv = ((fnv ^ buf[i]) * 16777619UL) & 0xffffffffUL;
        }
        total += (unsigned long)n;
        if (!quiet) {
            fwrite(buf, 1, (size_t)n, stdout);
        }
    }
    if (quiet) {
        printf("status %d bytes %lu fnv %08lx\n", status, total, fnv);
    } else {
        fprintf(stderr, "< :status: %d\n", status);
    }
    return n;
}

int main(int argc, char **argv)
{
    brisk_cfg cfg = BRISK_DEFAULTS;
    const char *method = NULL, *host, *path;
    uint8_t *body = NULL;
    size_t body_len = 0, k;
    brisk_h2_stream *s[4];
    brisk_h2_header cl = {"content-length", NULL};
    char cl_val[24];
    int i, j, rc = BRISK_OK, n = 1, rounds = 1, quiet = 0;
    uint16_t port = 443;
    brisk_conn *c;
    brisk_h2 *h = NULL;
    void *mem;

    cfg.alpn = "h2";
    for (i = 1; i < argc && argv[i][0] == '-'; i += 2) {
        const char *v = i + 1 < argc ? argv[i + 1] : "";
        switch (argv[i][1]) {
        case 'c':
            cfg.ca_file = v;
            break;
        case 'm':
            method = v;
            break;
        case 'd':
            body = read_file(v, &body_len);
            break;
        case 'D':
            body_len = (size_t)strtoul(v, NULL, 10);
            body = malloc(body_len + 1);
            for (k = 0; body != NULL && k < body_len; k++) {
                body[k] = (uint8_t)(k % 251);
            }
            break;
        case 'n':
            n = atoi(v);
            break;
        case 'r':
            rounds = atoi(v);
            break;
        case 'q':
            quiet = 1;
            i--; /* no value */
            break;
        default:
            i = argc;
            break;
        }
    }
    if (argc - i < 2 || n < 1 || n > 4 || rounds < 1 || (body_len > 0 && body == NULL)) {
        fprintf(stderr, "usage: h2_get [-c ca.pem] [-m method] [-d file | -D size] [-n 1..4] "
                        "[-r rounds] [-q] host [port] path\n");
        return 1;
    }
    host = argv[i];
    if (argc - i > 2) {
        port = (uint16_t)atoi(argv[i + 1]);
    }
    path = argv[argc - 1];
    if (method == NULL) {
        method = body_len > 0 ? "POST" : "GET";
    }
    snprintf(cl_val, sizeof cl_val, "%lu", (unsigned long)body_len);
    cl.value = cl_val;

    rc = brisk_connect(&cfg, host, port, &c);
    if (rc != BRISK_OK) {
        free(body);
        fprintf(stderr, "brisk: connect failed: %s\n", err_name(rc));
        return 2;
    }
    mem = malloc(brisk_h2_size());
    rc = mem == NULL ? BRISK_E_ARG : brisk_h2_open(c, mem, brisk_h2_size(), &h);
    if (rc != BRISK_OK) {
        fprintf(stderr, "brisk: h2_open: %s\n", err_name(rc));
    }
    for (j = 0; rc == BRISK_OK && j < rounds; j++) {
        int opened = 0;
        for (; rc == BRISK_OK && opened < n; opened++) {
            rc = brisk_h2_request(h, method, path, &cl, body_len > 0, body, body_len, &s[opened]);
        }
        if (rc != BRISK_OK) {
            opened--; /* the failed request holds no stream */
            fprintf(stderr, "brisk: request %d: %s\n", j * n + opened + 1, err_name(rc));
        }
        for (k = 0; k < (size_t)opened; k++) {
            int r = rc == BRISK_OK ? fetch(s[k], quiet) : BRISK_OK;
            if (r != BRISK_OK) {
                fprintf(stderr, "brisk: response %d: %s\n", j * n + (int)k + 1, err_name(r));
                rc = r;
            }
            brisk_h2_stream_close(s[k]);
        }
    }
    brisk_h2_close(h);
    brisk_close(c);
    free(mem);
    free(body);
    return rc == BRISK_OK ? 0 : 2;
}
