#!/usr/bin/env python3
"""Single-file distribution: dist/brisk.h + dist/brisk.c (stdlib only).

  python tools/amalg.py            write dist/brisk.h and dist/brisk.c

dist/brisk.h is include/brisk.h with brisk_config.h inlined, so it stays the only config: set
BRISK_PROFILE / BRISK_ENABLE_* with -D exactly as for the CMake build. dist/brisk.c is every
library source in CMakeLists.txt order (src/os/ last, Linux only, as in CMake) with its quoted
#includes inlined once - brisk_int.h and the vendored fiat files included. `#line` directives
keep compiler messages and debuggers pointing at the original files.

  cc -std=c99 -Os -c brisk.c          # next to brisk.h; nothing else is needed

_GNU_SOURCE goes first: src/os/ needs it (syscall, SOCK_CLOEXEC, getaddrinfo) and in one TU
the first system header freezes glibc's feature set; it is a superset of linux_ca.c's
_POSIX_C_SOURCE 200809L, so that file's own block becomes a no-op. The sources keep file-local
names unique (or #undef macros at file end - .claude/rules/c-code.md), so no renaming happens
here; `python tools/dev.py amalg` compiles the result warning-free per profile and runs the
test suite against it.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "dist"
INCLUDE = re.compile(r'^\s*#\s*include\s+"([^"]+)"', re.M)
PUBLIC = {"brisk.h", "brisk_config.h"}  # provided by dist/brisk.h


def sources():
    """(core, os) sources as CMakeLists.txt lists them; CMake comments start at '#'."""
    cm = (ROOT / "CMakeLists.txt").read_text(encoding="utf-8")
    text = "\n".join(line.split("#")[0] for line in cm.splitlines())
    core = text[text.index("add_library(brisk"):]
    core = core[:core.index(")")]
    os_part = text[text.index("target_sources(brisk PRIVATE src/os/"):]
    os_part = os_part[:os_part.index(")")]
    return (re.findall(r"src/[\w/]+\.c", core), re.findall(r"src/os/\w+\.c", os_part))


def rel(p):
    return p.relative_to(ROOT).as_posix()


def inline(path, seen, out):
    """Append path's lines to out, replacing each quoted #include by the file (once)."""
    lines = path.read_text(encoding="utf-8").splitlines()
    out.append(f'#line 1 "{rel(path)}"')
    for n, line in enumerate(lines, 1):
        m = INCLUDE.match(line)
        if not m:
            out.append(line)
            continue
        name = m.group(1)
        if Path(name).name in PUBLIC:
            out.append(f"/* {line.strip()} - dist/brisk.h */")
            continue
        for base in (path.parent, ROOT / "src", ROOT / "vendor"):
            dep = (base / name).resolve()
            if dep.is_file():
                break
        else:
            sys.exit(f"amalg: {rel(path)}:{n}: cannot resolve {name}")
        if dep not in seen:
            seen.add(dep)
            inline(dep, seen, out)
        out.append(f'#line {n + 1} "{rel(path)}"')


def main():
    DIST.mkdir(exist_ok=True)
    cfg = (ROOT / "include" / "brisk_config.h").read_text(encoding="utf-8")
    hdr = (ROOT / "include" / "brisk.h").read_text(encoding="utf-8")
    inc = '#include "brisk_config.h"'
    if hdr.count(inc) != 1:
        sys.exit("amalg: include/brisk.h must include brisk_config.h exactly once")
    hdr = hdr.replace(inc, "/* ---- include/brisk_config.h ---- */\n" + cfg.rstrip() +
                      "\n/* ---- end of brisk_config.h ---- */")
    (DIST / "brisk.h").write_text("/* dist/brisk.h - generated by tools/amalg.py, do not edit */\n"
                                  + hdr, encoding="utf-8", newline="\n")

    core, os_files = sources()
    out = ["/* dist/brisk.c - generated by tools/amalg.py, do not edit. Compile next to brisk.h. */",
           "#ifndef _GNU_SOURCE", "#    define _GNU_SOURCE", "#endif", '#include "brisk.h"']
    seen = set()
    for f in core:
        inline(ROOT / f, seen, out)
    out.append("#if defined(__linux__)")
    for f in os_files:
        inline(ROOT / f, seen, out)
    out.append("#endif /* __linux__ */")
    (DIST / "brisk.c").write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print(f"amalg: dist/brisk.h, dist/brisk.c ({len(core) + len(os_files)} sources, "
          f"{len(out)} lines)")


if __name__ == "__main__":
    main()
