#!/usr/bin/env python3
"""docs/API.md from include/brisk.h (stdlib only).

  python tools/apidoc.py            rewrite docs/API.md
  python tools/apidoc.py --check    exit 1 if docs/API.md is stale (CI)

brisk.h stays THE reference - its comments are the documentation. API.md is the index into it:
per section (the header's "/* ----" banners), every BRISK_API function, error code, macro and
public type with the first sentence of its comment and a link to its line. Nothing is written
by hand here, so the two cannot drift.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HDR = ROOT / "include" / "brisk.h"
OUT = ROOT / "docs" / "API.md"
LINK = "../include/brisk.h"


def first_sentence(comment):
    text = " ".join(l.strip().lstrip("/*").strip() for l in comment.splitlines())
    text = re.sub(r"\s+", " ", text.replace("*/", "")).strip()
    m = re.match(r"(.+?(?<!e\.g)(?<!i\.e)\.)(\s|$)", text)
    s = m.group(1) if m else text
    return (s[:157] + "...") if len(s) > 160 else s


def parse(src):
    lines = src.splitlines()
    sections, cur, parent = [], None, "General"
    comment, comment_end, group, struct_doc = "", -2, "", ""
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("/* ----"):
            # "/* -----...": a section, titled by the next line up to ':', ' (' or '. ';
            # "/* ---- name ---": a subsection of the last section. A section banner's text documents
            # the declarations under it; any other comment only the one directly below it
            j = i
            while "*/" not in lines[j]:
                j += 1
            sub = line.strip("/* -")
            if sub:
                title = f"{parent} - {sub.split(':')[0].strip()}"
            else:
                title = re.split(r":|\s\(|\.\s|\.$", lines[i + 1].lstrip(" *").strip())[0]
                parent = title
            cur = (title, [])
            sections.append(cur)
            # the banner's text after the title documents what follows it directly
            body = " ".join(l.lstrip(" *") for l in lines[i + 1:j + 1])
            group = body.split(":", 1)[1] if ":" in body.split(".")[0] else ""
            i = j + 1
            continue
        if line.lstrip().startswith("/*") and not line.startswith("#"):
            j = i
            while "*/" not in lines[j]:
                j += 1
            comment, comment_end = "\n".join(lines[i:j + 1]), j
            i = j + 1
            continue
        doc = comment if comment_end in (i - 1, i) else ""
        if re.match(r"typedef\s+(struct|enum)\b[^;]*$", line):
            struct_doc = doc  # documents the "} name;" that closes it
        if line[:1].strip() and not line.startswith(("BRISK_API", "#", "}", "typedef")):
            group = ""  # any other top-level line ends the group (struct bodies are indented)
        entry = None
        m = re.match(r"BRISK_API\s+[^(]*?\b(\w+)\s*\(", line)
        if m:
            entry = ("function", m.group(1))
        m2 = re.match(r"\s+(BRISK_E_\w+|BRISK_OK)\s*=\s*(-?\d+)", line)
        if m2:
            entry = ("error", f"{m2.group(1)} ({m2.group(2)})")
            tail = line.split("/*", 1)
            if len(tail) == 2:  # the comment starts on the same line
                j = i
                while "*/" not in lines[j]:
                    j += 1
                doc = "/*" + tail[1] + "\n" + "\n".join(lines[i + 1:j + 1])
        m3 = re.match(r"#define\s+(BRISK_[A-Z0-9_]+)\b", line)
        if m3 and not m3.group(1).startswith(("BRISK_H", "BRISK_API", "BRISK_SSL_VERSION")):
            entry = ("macro", m3.group(1))
        m4 = re.match(r"}\s*(brisk_\w+)\s*;", line) or re.match(r"typedef\s+.*\b(brisk_\w+)\s*;", line)
        if m4:
            entry = ("type", m4.group(1))
            if line.startswith("}"):
                doc = struct_doc
        if entry and cur is None:
            cur = ("General", [])
            sections.append(cur)
        if entry:
            text = doc or (group if entry[0] != "type" else "")  # a type: its own comment only
            cur[1].append((entry[0], entry[1], i + 1, first_sentence(text) if text else ""))
        i += 1
    return [s for s in sections if s[1]]


def render(sections):
    out = ["# Brisk-SSL API index", "",
           "Generated by `tools/apidoc.py` from [`include/brisk.h`](../include/brisk.h) - do not "
           "edit. The header is the reference: follow a link for the full contract. What each "
           "error means in the field and what to do about it: [TROUBLESHOOTING.md]"
           "(TROUBLESHOOTING.md).", ""]
    for title, entries in sections:
        out += [f"## {title}", "", "| | name | summary |", "|---|---|---|"]
        for kind, name, line, doc in entries:
            doc = doc.replace('|', '/') or "(see the header)"
            out.append(f"| {kind} | [`{name}`]({LINK}#L{line}) | {doc} |")
        out.append("")
    return "\n".join(out)


def main():
    text = render(parse(HDR.read_text(encoding="utf-8")))
    if "--check" in sys.argv[1:]:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            sys.exit("docs/API.md is stale: run python tools/apidoc.py")
        print("docs/API.md up to date")
        return
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"written: docs/API.md ({sum(1 for l in text.splitlines() if l.startswith('| ') and '[`' in l)} entries)")


if __name__ == "__main__":
    main()
